apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: devops
spec:
  selector:
    app: devops
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200
